[package]
name = "rutcher"
version = "0.1.0"
authors = ["Giulio De Pasquale <me@giugl.io>"]
license = "MIT"
repository = "https://github.com/peperunas/rutcher"

[dependencies]
hex_d_hex = "1.0.1"
clap = "2"